-- External collaborators: task-scoped access derived from person fields and
-- structured comment mentions. Full-access users retain the existing app model;
-- related-only users are restricted here (RLS), not merely in the UI.

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Profile access scope and contextual comment data
-- -----------------------------------------------------------------------------

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS access_scope text NOT NULL DEFAULT 'full';

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_access_scope_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_access_scope_check
  CHECK (access_scope IN ('full', 'related_only'));

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_related_only_shape_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_related_only_shape_check
  CHECK (
    access_scope <> 'related_only'
    OR (role IS NOT DISTINCT FROM 'user' AND team_id IS NULL)
  );

-- The UI has long exposed Support preferences, but the historical database
-- constraint omitted that value. Replace it without rewriting existing rows.
ALTER TABLE public.notification_preferences
  DROP CONSTRAINT IF EXISTS notification_preferences_category_check;
ALTER TABLE public.notification_preferences
  ADD CONSTRAINT notification_preferences_category_check
  CHECK (category IN ('tasks', 'deadlines', 'mentions', 'schedule', 'members', 'support'));

-- Historical Support mentions shared the task event type. Split them before
-- external notification policies are installed so ticket titles/IDs cannot
-- leak to a recipient who is later converted to related-only access.
UPDATE public.notifications
SET type = 'ticket_mention'
WHERE type = 'comment_mention'
  AND entity_data ? 'ticketId';

ALTER TABLE public.task_comments
  ADD COLUMN IF NOT EXISTS context_team_id uuid REFERENCES public.teams(id);

UPDATE public.task_comments c
SET context_team_id = t.team_id
FROM public.tasks t
WHERE t.id = c.task_id
  AND c.context_team_id IS NULL;

ALTER TABLE public.task_comments
  ALTER COLUMN context_team_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_task_comments_task_context
  ON public.task_comments(task_id, context_team_id, created_at);

-- -----------------------------------------------------------------------------
-- 2. Structured mentions, effective grants, and per-user revision stream
-- -----------------------------------------------------------------------------

CREATE TABLE public.task_comment_mentions (
  comment_id uuid NOT NULL REFERENCES public.task_comments(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  context_team_id uuid NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  grants_access boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (comment_id, profile_id, context_team_id)
);

CREATE INDEX idx_task_comment_mentions_task
  ON public.task_comment_mentions(task_id, context_team_id);
CREATE INDEX idx_task_comment_mentions_profile
  ON public.task_comment_mentions(profile_id, task_id);

CREATE TABLE public.task_access_grants (
  task_id uuid NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  context_team_id uuid NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  source_type text NOT NULL CHECK (
    source_type IN ('assignee', 'editor', 'designer', 'custom_person', 'comment_mention')
  ),
  source_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, profile_id, context_team_id, source_type, source_id)
);

CREATE INDEX idx_task_access_grants_profile_context
  ON public.task_access_grants(profile_id, context_team_id, task_id);
CREATE INDEX idx_task_access_grants_task_context
  ON public.task_access_grants(task_id, context_team_id, profile_id);

CREATE TABLE public.task_access_revisions (
  profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.task_access_revisions REPLICA IDENTITY FULL;

CREATE TABLE public.external_access_migration_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type text NOT NULL,
  entity_id uuid,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Outbound transports need their own replay ledger; the in-app notification
-- unique index cannot prevent repeated email/Telegram Edge Function calls.
-- A claim is intentionally single-shot per channel. Failed sends remain
-- claimed for manual operator retry rather than enabling attacker-driven loops.
CREATE TABLE public.external_notification_deliveries (
  comment_id uuid NOT NULL REFERENCES public.task_comments(id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  channel text NOT NULL CHECK (channel IN ('email', 'telegram')),
  claimed_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  PRIMARY KEY (comment_id, recipient_id, channel)
);

-- Non-comment task transports allow legitimate repeated updates, so use a
-- short rolling window instead of the permanent comment-delivery key. Different
-- event types and channels remain independent within the same rolling window.
CREATE TABLE public.restricted_task_notification_deliveries (
  claim_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  recipient_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  context_team_id uuid NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  notification_type text NOT NULL CHECK (
    notification_type IN (
      'task_assigned', 'task_status_changed', 'task_updated',
      'task_deadline_reminder'
    )
  ),
  channel text NOT NULL CHECK (channel IN ('email', 'telegram')),
  window_started_at timestamptz NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  PRIMARY KEY (
    recipient_id, task_id, context_team_id, notification_type,
    channel, window_started_at
  )
);

CREATE INDEX idx_restricted_task_notification_deliveries_claimed
  ON public.restricted_task_notification_deliveries(claimed_at);

-- Public sign-up is enabled in this project. A raw auth sign-up must therefore
-- land in the least-privileged scope; only the verified admin invite flow may
-- promote it through finalize_invited_profile().
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_profile_id uuid;
BEGIN
  INSERT INTO public.profiles(
    auth_user_id, name, role, access_scope, team_id, job_title, avatar, status
  ) VALUES (
    NEW.id,
    COALESCE(
      NULLIF(NEW.raw_user_meta_data ->> 'name', ''),
      NULLIF(NEW.raw_user_meta_data ->> 'full_name', ''),
      NULLIF(split_part(COALESCE(NEW.email, ''), '@', 1), ''),
      'User'
    ),
    'user',
    'related_only',
    NULL,
    NULLIF(NEW.raw_user_meta_data ->> 'job_title', ''),
    COALESCE(
      NULLIF(NEW.raw_user_meta_data ->> 'avatar', ''),
      NULLIF(NEW.raw_user_meta_data ->> 'avatar_url', '')
    ),
    'active'
  )
  ON CONFLICT (auth_user_id) DO UPDATE
  SET name = EXCLUDED.name,
      role = 'user',
      access_scope = 'related_only',
      team_id = NULL,
      job_title = COALESCE(EXCLUDED.job_title, public.profiles.job_title),
      avatar = COALESCE(EXCLUDED.avatar, public.profiles.avatar)
  RETURNING id INTO v_profile_id;

  INSERT INTO public.permissions(member_id, can_create, can_edit, can_delete)
  VALUES (v_profile_id, true, false, false)
  ON CONFLICT (member_id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- 3. Small, RLS-safe helpers
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.current_profile_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p.id
  FROM public.profiles p
  WHERE p.auth_user_id = auth.uid()
  LIMIT 1
$$;

-- Harden the pre-existing role helpers because they are called from new
-- SECURITY DEFINER RPCs and RLS policies.
CREATE OR REPLACE FUNCTION public.auth_profile()
RETURNS TABLE(profile_id uuid, team_id uuid, role text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p.id, p.team_id, p.role
  FROM public.profiles p
  WHERE p.auth_user_id = auth.uid()
  LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid() AND p.role = 'admin'
  )
$$;

CREATE OR REPLACE FUNCTION public.is_editor()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.auth_user_id = auth.uid() AND p.role IN ('editor', 'admin')
  )
$$;

CREATE OR REPLACE FUNCTION public.current_access_scope()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE((
    SELECT p.access_scope
    FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
    LIMIT 1
  ), 'related_only')
$$;

CREATE OR REPLACE FUNCTION public.is_full_access()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.auth_user_id = auth.uid()
      AND p.access_scope = 'full'
  )
$$;

CREATE OR REPLACE FUNCTION public.try_uuid(p_value text)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  IF p_value IS NULL OR p_value = '' THEN
    RETURN NULL;
  END IF;
  RETURN p_value::uuid;
EXCEPTION WHEN invalid_text_representation THEN
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.jsonb_profile_ids(p_value jsonb)
RETURNS SETOF uuid
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT DISTINCT public.try_uuid(v.value)
  FROM (
    SELECT trim(both '"' from p_value::text) AS value
    WHERE jsonb_typeof(p_value) = 'string'
    UNION ALL
    SELECT jsonb_array_elements_text(p_value) AS value
    WHERE jsonb_typeof(p_value) = 'array'
  ) AS v
  WHERE public.try_uuid(v.value) IS NOT NULL
$$;

CREATE OR REPLACE FUNCTION public.has_related_task_access(p_task_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.task_access_grants g
    JOIN public.tasks t ON t.id = g.task_id AND t.deleted_at IS NULL
    WHERE g.task_id = p_task_id
      AND g.profile_id = public.current_profile_id()
  )
$$;

CREATE OR REPLACE FUNCTION public.has_related_context_access(
  p_task_id uuid,
  p_context_team_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.task_access_grants g
    JOIN public.tasks t ON t.id = g.task_id AND t.deleted_at IS NULL
    WHERE g.task_id = p_task_id
      AND g.context_team_id = p_context_team_id
      AND g.profile_id = public.current_profile_id()
  )
$$;

CREATE OR REPLACE FUNCTION public.is_authorized_task_team(p_team_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.task_access_grants g
    JOIN public.tasks t ON t.id = g.task_id AND t.deleted_at IS NULL
    WHERE g.profile_id = public.current_profile_id()
      AND (g.context_team_id = p_team_id OR t.team_id = p_team_id)
  )
$$;

-- -----------------------------------------------------------------------------
-- 4. Derive effective grants from every person-bearing source
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.compute_task_access_grants(p_task_id uuid)
RETURNS TABLE (
  task_id uuid,
  profile_id uuid,
  context_team_id uuid,
  source_type text,
  source_id uuid
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH task_row AS (
    SELECT t.*
    FROM public.tasks t
    WHERE t.id = p_task_id
      AND t.deleted_at IS NULL
  ), sources AS (
    SELECT t.id AS task_id,
           a.member_id AS profile_id,
           t.team_id AS context_team_id,
           'assignee'::text AS source_type,
           a.member_id AS source_id
    FROM task_row t
    JOIN public.task_assignees a ON a.task_id = t.id

    UNION ALL

    SELECT t.id, ids.profile_id, t.team_id, 'editor'::text, ids.profile_id
    FROM task_row t
    CROSS JOIN LATERAL public.jsonb_profile_ids(t.editor_ids) AS ids(profile_id)

    UNION ALL

    SELECT t.id, ids.profile_id, t.team_id, 'designer'::text, ids.profile_id
    FROM task_row t
    CROSS JOIN LATERAL public.jsonb_profile_ids(t.designer_ids) AS ids(profile_id)

    UNION ALL

    SELECT t.id, ids.profile_id, t.team_id, 'custom_person'::text, cp.id
    FROM task_row t
    JOIN public.custom_properties cp
      ON cp.team_id = t.team_id
     AND cp.type = 'person'
    CROSS JOIN LATERAL public.jsonb_profile_ids(t.custom_field_values -> cp.id::text) AS ids(profile_id)

    UNION ALL

    SELECT t.id, ids.profile_id, link.team_id, 'custom_person'::text, cp.id
    FROM task_row t
    JOIN public.task_team_links link ON link.task_id = t.id
    JOIN public.custom_properties cp
      ON cp.team_id = link.team_id
     AND cp.type = 'person'
    CROSS JOIN LATERAL public.jsonb_profile_ids(link.custom_field_values -> cp.id::text) AS ids(profile_id)

    UNION ALL

    SELECT t.id, m.profile_id, m.context_team_id, 'comment_mention'::text, m.comment_id
    FROM task_row t
    JOIN public.task_comment_mentions m ON m.task_id = t.id
    WHERE m.grants_access
      AND (
        m.context_team_id = t.team_id
        OR EXISTS (
          SELECT 1
          FROM public.task_team_links link
          WHERE link.task_id = t.id
            AND link.team_id = m.context_team_id
        )
      )
  )
  SELECT DISTINCT s.task_id, s.profile_id, s.context_team_id, s.source_type, s.source_id
  FROM sources s
  JOIN public.profiles p ON p.id = s.profile_id
$$;

CREATE OR REPLACE FUNCTION public.bump_task_access_revision(p_profile_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.task_access_revisions(profile_id, revision, updated_at)
  VALUES (p_profile_id, 1, now())
  ON CONFLICT (profile_id) DO UPDATE
  SET revision = public.task_access_revisions.revision + 1,
      updated_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.rebuild_task_access_grants(p_task_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.task_access_grants(
    task_id, profile_id, context_team_id, source_type, source_id
  )
  SELECT g.task_id, g.profile_id, g.context_team_id, g.source_type, g.source_id
  FROM public.compute_task_access_grants(p_task_id) g
  ON CONFLICT DO NOTHING;

  DELETE FROM public.task_access_grants existing
  WHERE existing.task_id = p_task_id
    AND NOT EXISTS (
      SELECT 1
      FROM public.compute_task_access_grants(p_task_id) desired
      WHERE desired.task_id = existing.task_id
        AND desired.profile_id = existing.profile_id
        AND desired.context_team_id = existing.context_team_id
        AND desired.source_type = existing.source_type
        AND desired.source_id = existing.source_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_task_access_grant_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = OLD.profile_id AND p.access_scope = 'related_only'
    ) THEN
      PERFORM public.bump_task_access_revision(OLD.profile_id);
    END IF;
    RETURN OLD;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = NEW.profile_id AND p.access_scope = 'related_only'
  ) THEN
    PERFORM public.bump_task_access_revision(NEW.profile_id);
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.profile_id <> NEW.profile_id AND EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = OLD.profile_id AND p.access_scope = 'related_only'
  ) THEN
    PERFORM public.bump_task_access_revision(OLD.profile_id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_task_access_grant_revision
AFTER INSERT OR UPDATE OR DELETE ON public.task_access_grants
FOR EACH ROW EXECUTE FUNCTION public.notify_task_access_grant_change();

-- -----------------------------------------------------------------------------
-- 5. Backfill structured legacy mentions, with an audit trail for skipped tokens
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.legacy_comment_mention_starts(p_content text)
RETURNS SETOF integer
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT position
  FROM generate_series(1, char_length(COALESCE(p_content, ''))) positions(position)
  WHERE substring(COALESCE(p_content, '') FROM position FOR 1) = '@'
    AND (
      position = 1
      OR substring(p_content FROM position - 1 FOR 1) ~ '[[:space:]]'
      OR substring(p_content FROM position - 1 FOR 1) = ANY(ARRAY['(', '[', '{'])
    )
$$;

-- Compare a known profile name literally at an @ position, which avoids
-- regex-name escaping bugs and exactly mirrors the client's post-token boundary.
CREATE OR REPLACE FUNCTION public.legacy_profile_mention_at(
  p_content text,
  p_profile_name text,
  p_token_start integer
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  WITH input AS (
    SELECT COALESCE(p_content, '') AS content,
           '@' || regexp_replace(COALESCE(p_profile_name, ''), '[[:space:]]', '', 'g') AS token
  )
  SELECT char_length(input.token) > 1
    AND p_token_start >= 1
    AND lower(substring(input.content FROM p_token_start FOR char_length(input.token))) = lower(input.token)
    AND (
      p_token_start = 1
      OR substring(input.content FROM p_token_start - 1 FOR 1) ~ '[[:space:]]'
      OR substring(input.content FROM p_token_start - 1 FOR 1) = ANY(ARRAY['(', '[', '{'])
    )
    AND (
      p_token_start + char_length(input.token) > char_length(input.content)
      OR substring(input.content FROM p_token_start + char_length(input.token) FOR 1) ~ '[[:space:]]'
      OR substring(input.content FROM p_token_start + char_length(input.token) FOR 1)
         = ANY(ARRAY['.', ',', '!', '?', ';', ':', ')', ']', '}'])
    )
  FROM input
$$;

CREATE OR REPLACE FUNCTION public.legacy_profile_mention_positions(
  p_content text,
  p_profile_name text
)
RETURNS SETOF integer
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT position
  FROM public.legacy_comment_mention_starts(p_content) positions(position)
  WHERE public.legacy_profile_mention_at(p_content, p_profile_name, position)
$$;

WITH candidate_matches AS (
  SELECT DISTINCT c.id AS comment_id,
         c.task_id,
         c.context_team_id,
         c.user_id AS author_id,
         positions.token_start,
         p.id AS profile_id
  FROM public.task_comments c
  CROSS JOIN LATERAL public.legacy_comment_mention_starts(c.content) positions(token_start)
  CROSS JOIN public.profiles p
  WHERE public.legacy_profile_mention_at(c.content, p.name, positions.token_start)
), candidates AS (
  SELECT match.comment_id, match.task_id, match.context_team_id, match.author_id,
         match.token_start,
         array_agg(DISTINCT match.profile_id ORDER BY match.profile_id) AS profile_ids,
         count(DISTINCT match.profile_id) AS candidate_count
  FROM candidate_matches match
  GROUP BY match.comment_id, match.task_id, match.context_team_id,
           match.author_id, match.token_start
)
INSERT INTO public.task_comment_mentions(
  comment_id, task_id, profile_id, context_team_id, grants_access
)
SELECT c.comment_id,
       c.task_id,
       c.profile_ids[1],
       c.context_team_id,
       COALESCE(author.access_scope = 'full', false)
FROM candidates c
JOIN public.profiles author ON author.id = c.author_id
WHERE c.candidate_count = 1
ON CONFLICT DO NOTHING;

WITH candidate_matches AS (
  SELECT DISTINCT c.id AS comment_id,
         positions.token_start,
         p.id AS profile_id
  FROM public.task_comments c
  CROSS JOIN LATERAL public.legacy_comment_mention_starts(c.content) positions(token_start)
  CROSS JOIN public.profiles p
  WHERE public.legacy_profile_mention_at(c.content, p.name, positions.token_start)
), candidates AS (
  SELECT match.comment_id, match.token_start,
         array_agg(DISTINCT match.profile_id ORDER BY match.profile_id) AS profile_ids,
         count(DISTINCT match.profile_id) AS candidate_count
  FROM candidate_matches match
  GROUP BY match.comment_id, match.token_start
)
INSERT INTO public.external_access_migration_report(report_type, entity_id, details)
SELECT 'mention_ambiguous',
       c.comment_id,
       jsonb_build_object(
         'tokenStart', c.token_start,
         'candidateProfileIds', to_jsonb(c.profile_ids)
       )
FROM candidates c
WHERE c.candidate_count > 1;

-- Log syntactic @tokens for which no profile name matched at that exact start.
WITH token_starts AS (
  SELECT c.id AS comment_id,
         position AS token_start,
         substring(c.content FROM position FOR 80) AS token_context
  FROM public.task_comments c
  CROSS JOIN LATERAL public.legacy_comment_mention_starts(c.content) positions(position)
), matched_starts AS (
  SELECT DISTINCT c.id AS comment_id, positions.token_start
  FROM public.task_comments c
  CROSS JOIN LATERAL public.legacy_comment_mention_starts(c.content) positions(token_start)
  CROSS JOIN public.profiles p
  WHERE public.legacy_profile_mention_at(c.content, p.name, positions.token_start)
)
INSERT INTO public.external_access_migration_report(report_type, entity_id, details)
SELECT 'mention_unmatched', token.comment_id,
       jsonb_build_object(
         'tokenStart', token.token_start,
         'tokenContext', token.token_context
       )
FROM token_starts token
LEFT JOIN matched_starts matched
  ON matched.comment_id = token.comment_id
 AND matched.token_start = token.token_start
WHERE matched.comment_id IS NULL;

INSERT INTO public.task_access_grants(
  task_id, profile_id, context_team_id, source_type, source_id
)
SELECT g.task_id, g.profile_id, g.context_team_id, g.source_type, g.source_id
FROM public.tasks t
CROSS JOIN LATERAL public.compute_task_access_grants(t.id) g
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 6. Keep derived grants current
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.rebuild_grants_for_task_row()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.rebuild_task_access_grants(COALESCE(NEW.id, OLD.id));
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_tasks_rebuild_access
AFTER INSERT OR UPDATE OF team_id, editor_ids, designer_ids, custom_field_values, deleted_at
ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.rebuild_grants_for_task_row();

CREATE OR REPLACE FUNCTION public.rebuild_grants_for_task_child()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_task_id uuid;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.task_id IS DISTINCT FROM NEW.task_id THEN
    PERFORM public.rebuild_task_access_grants(OLD.task_id);
    PERFORM public.rebuild_task_access_grants(NEW.task_id);
    RETURN NEW;
  END IF;
  v_task_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.task_id ELSE NEW.task_id END;
  PERFORM public.rebuild_task_access_grants(v_task_id);
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_task_assignees_rebuild_access
AFTER INSERT OR UPDATE OR DELETE ON public.task_assignees
FOR EACH ROW EXECUTE FUNCTION public.rebuild_grants_for_task_child();

CREATE TRIGGER trg_task_team_links_rebuild_access
AFTER INSERT OR UPDATE OR DELETE ON public.task_team_links
FOR EACH ROW EXECUTE FUNCTION public.rebuild_grants_for_task_child();

CREATE TRIGGER trg_task_mentions_rebuild_access
AFTER INSERT OR UPDATE OR DELETE ON public.task_comment_mentions
FOR EACH ROW EXECUTE FUNCTION public.rebuild_grants_for_task_child();

CREATE OR REPLACE FUNCTION public.rebuild_grants_for_custom_property()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_team_id uuid;
  v_task_id uuid;
BEGIN
  FOR v_team_id IN
    SELECT DISTINCT x.team_id
    FROM (VALUES (CASE WHEN TG_OP <> 'DELETE' THEN NEW.team_id END),
                 (CASE WHEN TG_OP <> 'INSERT' THEN OLD.team_id END)) AS x(team_id)
    WHERE x.team_id IS NOT NULL
  LOOP
    FOR v_task_id IN
      SELECT t.id
      FROM public.tasks t
      WHERE t.team_id = v_team_id
         OR EXISTS (
           SELECT 1 FROM public.task_team_links link
           WHERE link.task_id = t.id AND link.team_id = v_team_id
         )
    LOOP
      PERFORM public.rebuild_task_access_grants(v_task_id);
    END LOOP;
  END LOOP;
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_custom_properties_rebuild_access
AFTER INSERT OR UPDATE OF team_id, type OR DELETE ON public.custom_properties
FOR EACH ROW EXECUTE FUNCTION public.rebuild_grants_for_custom_property();

CREATE OR REPLACE FUNCTION public.move_home_comment_contexts()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.team_id IS DISTINCT FROM NEW.team_id THEN
    INSERT INTO public.task_comment_mentions(
      comment_id,
      task_id,
      profile_id,
      context_team_id,
      grants_access,
      created_at
    )
    SELECT mention.comment_id,
           mention.task_id,
           mention.profile_id,
           NEW.team_id,
           mention.grants_access,
           mention.created_at
    FROM public.task_comment_mentions mention
    WHERE mention.task_id = NEW.id
      AND mention.context_team_id = OLD.team_id
    ON CONFLICT (comment_id, profile_id, context_team_id) DO UPDATE
    SET grants_access = public.task_comment_mentions.grants_access OR EXCLUDED.grants_access,
        created_at = LEAST(public.task_comment_mentions.created_at, EXCLUDED.created_at);

    DELETE FROM public.task_comment_mentions mention
    WHERE mention.task_id = NEW.id
      AND mention.context_team_id = OLD.team_id;

    UPDATE public.task_comments
    SET context_team_id = NEW.team_id
    WHERE task_id = NEW.id
      AND context_team_id = OLD.team_id;

    PERFORM public.rebuild_task_access_grants(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tasks_move_home_comment_contexts
AFTER UPDATE OF team_id ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.move_home_comment_contexts();

-- task_comments.context_team_id intentionally preserves a comment independently
-- from a linked workspace, so its FK cannot cascade on team deletion. Remap
-- linked-context comments to the task's home workspace before team/link cascades
-- run. Mentions are copied with an OR merge before the old-context rows are
-- removed, preserving the strongest grants_access value without PK conflicts.
CREATE OR REPLACE FUNCTION public.remap_linked_comment_contexts_before_team_delete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- A concurrent task home-team move must not let the mention and comment
  -- statements observe different destinations. Lock in a stable order to also
  -- avoid deadlocks when one statement deletes multiple teams.
  PERFORM task_row.id
  FROM public.tasks task_row
  WHERE task_row.team_id <> OLD.id
    AND (
      EXISTS (
        SELECT 1
        FROM public.task_comments comment_row
        WHERE comment_row.task_id = task_row.id
          AND comment_row.context_team_id = OLD.id
      )
      OR EXISTS (
        SELECT 1
        FROM public.task_comment_mentions mention
        WHERE mention.task_id = task_row.id
          AND mention.context_team_id = OLD.id
      )
    )
  ORDER BY task_row.id
  FOR UPDATE;

  INSERT INTO public.task_comment_mentions(
    comment_id,
    task_id,
    profile_id,
    context_team_id,
    grants_access,
    created_at
  )
  SELECT mention.comment_id,
         mention.task_id,
         mention.profile_id,
         task_row.team_id,
         mention.grants_access,
         mention.created_at
  FROM public.task_comment_mentions mention
  JOIN public.tasks task_row ON task_row.id = mention.task_id
  WHERE mention.context_team_id = OLD.id
    AND task_row.team_id <> OLD.id
  ON CONFLICT (comment_id, profile_id, context_team_id) DO UPDATE
  SET grants_access = public.task_comment_mentions.grants_access OR EXCLUDED.grants_access,
      created_at = LEAST(public.task_comment_mentions.created_at, EXCLUDED.created_at);

  DELETE FROM public.task_comment_mentions mention
  USING public.tasks task_row
  WHERE mention.task_id = task_row.id
    AND mention.context_team_id = OLD.id
    AND task_row.team_id <> OLD.id;

  UPDATE public.task_comments comment_row
  SET context_team_id = task_row.team_id
  FROM public.tasks task_row
  WHERE comment_row.task_id = task_row.id
    AND comment_row.context_team_id = OLD.id
    AND task_row.team_id <> OLD.id;

  UPDATE public.notifications notification_row
  SET entity_data = notification_row.entity_data
    || CASE
         WHEN public.try_uuid(notification_row.entity_data ->> 'contextTeamId') = OLD.id
           THEN jsonb_build_object('contextTeamId', task_row.team_id::text)
         ELSE '{}'::jsonb
       END
    || CASE
         WHEN public.try_uuid(notification_row.entity_data ->> 'teamId') = OLD.id
           THEN jsonb_build_object('teamId', task_row.team_id::text)
         ELSE '{}'::jsonb
       END
  FROM public.tasks task_row
  WHERE task_row.team_id <> OLD.id
    AND public.try_uuid(notification_row.entity_data ->> 'taskId') = task_row.id
    AND notification_row.type IN (
      'task_assigned',
      'task_status_changed',
      'task_updated',
      'task_unassigned',
      'task_deleted',
      'task_deadline_reminder',
      'comment_mention'
    )
    AND (
      public.try_uuid(notification_row.entity_data ->> 'contextTeamId') = OLD.id
      OR public.try_uuid(notification_row.entity_data ->> 'teamId') = OLD.id
    );

  RETURN OLD;
END;
$$;

CREATE TRIGGER trg_teams_remap_linked_comment_contexts
BEFORE DELETE ON public.teams
FOR EACH ROW EXECUTE FUNCTION public.remap_linked_comment_contexts_before_team_delete();

CREATE OR REPLACE FUNCTION public.enforce_task_mention_consistency()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.task_comments c
    WHERE c.id = NEW.comment_id
      AND c.task_id = NEW.task_id
  ) THEN
    RAISE EXCEPTION 'Mention task does not match its comment';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_task_mentions_consistency
BEFORE INSERT OR UPDATE ON public.task_comment_mentions
FOR EACH ROW EXECUTE FUNCTION public.enforce_task_mention_consistency();

-- -----------------------------------------------------------------------------
-- 7. Profile/team invariants and safe member administration
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.enforce_profile_access_transition()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.access_scope = 'related_only'
     AND (NEW.role <> 'user' OR NEW.team_id IS NOT NULL) THEN
    RAISE EXCEPTION 'Related-only profiles must have role user and no team';
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.access_scope = 'related_only'
     AND NEW.access_scope = 'full'
     AND NEW.team_id IS NULL THEN
    RAISE EXCEPTION 'A team is required when converting an external collaborator to full access';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_profiles_enforce_access_transition
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.enforce_profile_access_transition();

CREATE OR REPLACE FUNCTION public.after_profile_access_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.access_scope = 'related_only' THEN
    DELETE FROM public.team_members WHERE profile_id = NEW.id;
  END IF;
  IF TG_OP = 'INSERT' OR OLD.access_scope IS DISTINCT FROM NEW.access_scope THEN
    PERFORM public.bump_task_access_revision(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_profiles_after_access_change
AFTER INSERT OR UPDATE OF access_scope ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.after_profile_access_change();

CREATE OR REPLACE FUNCTION public.reject_external_team_membership()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = NEW.profile_id AND p.access_scope = 'related_only'
  ) THEN
    RAISE EXCEPTION 'External collaborators cannot belong to teams';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_team_members_reject_external
BEFORE INSERT OR UPDATE OF profile_id ON public.team_members
FOR EACH ROW EXECUTE FUNCTION public.reject_external_team_membership();

CREATE OR REPLACE FUNCTION public.update_own_profile(
  p_name text DEFAULT NULL,
  p_job_title text DEFAULT NULL,
  p_avatar text DEFAULT NULL
)
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
BEGIN
  IF p_name IS NOT NULL AND (btrim(p_name) = '' OR length(p_name) > 100) THEN
    RAISE EXCEPTION 'Name must be between 1 and 100 characters';
  END IF;
  IF p_job_title IS NOT NULL AND length(p_job_title) > 100 THEN
    RAISE EXCEPTION 'Job title must be 100 characters or fewer';
  END IF;

  UPDATE public.profiles p
  SET name = COALESCE(p_name, p.name),
      job_title = COALESCE(p_job_title, p.job_title),
      avatar = COALESCE(p_avatar, p.avatar)
  WHERE p.auth_user_id = auth.uid()
  RETURNING p.* INTO v_profile;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;
  RETURN v_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_member_access_scope(
  p_profile_id uuid,
  p_access_scope text,
  p_team_ids uuid[] DEFAULT '{}'::uuid[],
  p_role text DEFAULT 'user'
)
RETURNS SETOF public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_primary_team_id uuid;
  v_expected_count integer;
  v_existing_count integer;
  v_profile public.profiles%ROWTYPE;
BEGIN
  IF NOT public.is_admin() OR NOT public.is_full_access() THEN
    RAISE EXCEPTION 'Only full-access admins can change member access';
  END IF;
  IF p_access_scope NOT IN ('full', 'related_only') THEN
    RAISE EXCEPTION 'Invalid access scope';
  END IF;
  IF p_role NOT IN ('admin', 'editor', 'user') THEN
    RAISE EXCEPTION 'Invalid role';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = p_profile_id) THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;
  IF EXISTS (
       SELECT 1 FROM public.profiles
       WHERE id = p_profile_id AND access_scope = 'full' AND role = 'admin'
     )
     AND (p_access_scope <> 'full' OR p_role <> 'admin')
     AND NOT EXISTS (
       SELECT 1 FROM public.profiles
       WHERE id <> p_profile_id AND access_scope = 'full' AND role = 'admin'
     ) THEN
    RAISE EXCEPTION 'The last full-access admin cannot be demoted';
  END IF;

  IF p_access_scope = 'related_only' THEN
    IF p_role <> 'user' OR cardinality(COALESCE(p_team_ids, '{}'::uuid[])) <> 0 THEN
      RAISE EXCEPTION 'External collaborators must use role user and have no teams';
    END IF;
    UPDATE public.profiles
    SET access_scope = 'related_only', role = 'user', team_id = NULL
    WHERE id = p_profile_id
    RETURNING * INTO v_profile;

    -- Keep the conversion self-contained even if this RPC is reused without
    -- the defensive profile trigger in a future schema revision.
    DELETE FROM public.team_members WHERE profile_id = p_profile_id;
  ELSE
    IF cardinality(COALESCE(p_team_ids, '{}'::uuid[])) = 0 THEN
      RAISE EXCEPTION 'At least one team is required for full access';
    END IF;
    IF cardinality(p_team_ids) <> cardinality(ARRAY(SELECT DISTINCT unnest(p_team_ids))) THEN
      RAISE EXCEPTION 'Duplicate team IDs are not allowed';
    END IF;

    SELECT count(*) INTO v_existing_count
    FROM public.teams WHERE id = ANY(p_team_ids);
    v_expected_count := cardinality(p_team_ids);
    IF v_existing_count <> v_expected_count THEN
      RAISE EXCEPTION 'One or more teams do not exist';
    END IF;

    v_primary_team_id := p_team_ids[1];
    UPDATE public.profiles
    SET access_scope = 'full', role = p_role, team_id = v_primary_team_id
    WHERE id = p_profile_id
    RETURNING * INTO v_profile;

    UPDATE public.team_members
    SET is_primary = false
    WHERE profile_id = p_profile_id AND is_primary;

    DELETE FROM public.team_members
    WHERE profile_id = p_profile_id
      AND NOT (team_id = ANY(p_team_ids));

    INSERT INTO public.team_members(team_id, profile_id, is_primary, sort_order)
    SELECT team_id, p_profile_id, false, ordinality - 1
    FROM unnest(p_team_ids) WITH ORDINALITY AS requested(team_id, ordinality)
    ON CONFLICT (team_id, profile_id) DO UPDATE
    SET sort_order = EXCLUDED.sort_order;

    UPDATE public.team_members
    SET is_primary = true
    WHERE profile_id = p_profile_id AND team_id = v_primary_team_id;
  END IF;

  RETURN NEXT v_profile;
END;
$$;

-- Service-role-only companion for the invite Edge Function. The auth trigger may
-- already have inserted the profile, so this is deliberately an upsert.
CREATE OR REPLACE FUNCTION public.finalize_invited_profile(
  p_auth_user_id uuid,
  p_name text,
  p_role text,
  p_job_title text,
  p_avatar text,
  p_team_id uuid,
  p_access_scope text
)
RETURNS SETOF public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required';
  END IF;
  IF p_access_scope NOT IN ('full', 'related_only') THEN
    RAISE EXCEPTION 'Invalid access scope';
  END IF;
  IF p_role NOT IN ('admin', 'editor', 'user') THEN
    RAISE EXCEPTION 'Invalid role';
  END IF;
  IF p_access_scope = 'related_only' AND (p_role <> 'user' OR p_team_id IS NOT NULL) THEN
    RAISE EXCEPTION 'External collaborators must use role user and have no team';
  END IF;
  IF p_access_scope = 'full' AND p_team_id IS NULL THEN
    RAISE EXCEPTION 'A team is required for full-access invitations';
  END IF;
  IF p_team_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.teams WHERE id = p_team_id) THEN
    RAISE EXCEPTION 'Team not found';
  END IF;

  INSERT INTO public.profiles(
    auth_user_id, name, role, job_title, avatar, team_id, status, access_scope
  ) VALUES (
    p_auth_user_id, p_name, p_role, p_job_title, p_avatar, p_team_id, 'active', p_access_scope
  )
  ON CONFLICT (auth_user_id) DO UPDATE
  SET name = EXCLUDED.name,
      role = EXCLUDED.role,
      job_title = EXCLUDED.job_title,
      avatar = EXCLUDED.avatar,
      team_id = EXCLUDED.team_id,
      status = 'active',
      access_scope = EXCLUDED.access_scope
  RETURNING * INTO v_profile;

  DELETE FROM public.team_members WHERE profile_id = v_profile.id;
  IF p_access_scope = 'full' THEN
    INSERT INTO public.team_members(team_id, profile_id, is_primary, sort_order)
    VALUES (p_team_id, v_profile.id, true, 0);
  END IF;

  INSERT INTO public.permissions(member_id, can_create, can_edit, can_delete)
  VALUES (
    v_profile.id,
    true,
    false,
    false
  )
  ON CONFLICT (member_id) DO UPDATE
  SET can_create = EXCLUDED.can_create,
      can_edit = EXCLUDED.can_edit,
      can_delete = EXCLUDED.can_delete;

  RETURN NEXT v_profile;
END;
$$;

-- -----------------------------------------------------------------------------
-- 8. Transactional task/comment RPCs
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.save_task_with_relations(
  p_task jsonb,
  p_assignee_ids uuid[] DEFAULT '{}'::uuid[],
  p_placement_names text[] DEFAULT '{}'::text[]
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_task_id uuid;
  v_team_id uuid;
  v_invalid_count integer;
  v_can_mutate_placements boolean;
  v_existing_placement_names text[];
  v_requested_placement_names text[];
BEGIN
  IF NOT public.is_full_access() THEN
    RAISE EXCEPTION 'External collaborators cannot modify tasks';
  END IF;

  v_task_id := COALESCE(public.try_uuid(p_task ->> 'id'), gen_random_uuid());
  v_team_id := public.try_uuid(p_task ->> 'team_id');
  IF v_team_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.teams WHERE id = v_team_id) THEN
    RAISE EXCEPTION 'A valid team_id is required';
  END IF;
  IF btrim(COALESCE(p_task ->> 'title', '')) = '' THEN
    RAISE EXCEPTION 'Task title is required';
  END IF;

  v_can_mutate_placements := public.is_editor() OR v_team_id = (
    SELECT ap.team_id FROM public.auth_profile() ap
  );
  SELECT COALESCE(array_agg(DISTINCT p.name ORDER BY p.name), '{}'::text[])
  INTO v_existing_placement_names
  FROM public.task_placements tp
  JOIN public.placements p ON p.id = tp.placement_id
  WHERE tp.task_id = v_task_id;
  SELECT COALESCE(array_agg(name ORDER BY name), '{}'::text[])
  INTO v_requested_placement_names
  FROM (
    SELECT DISTINCT requested.name
    FROM unnest(COALESCE(p_placement_names, '{}'::text[])) requested(name)
    WHERE requested.name <> ''
  ) normalized;
  IF NOT v_can_mutate_placements
     AND v_existing_placement_names IS DISTINCT FROM v_requested_placement_names THEN
    RAISE EXCEPTION 'You cannot change placements for a task outside your team';
  END IF;

  SELECT count(*) INTO v_invalid_count
  FROM (SELECT DISTINCT unnest(COALESCE(p_assignee_ids, '{}'::uuid[])) AS id) requested
  LEFT JOIN public.profiles p ON p.id = requested.id
  WHERE p.id IS NULL;
  IF v_invalid_count > 0 THEN
    RAISE EXCEPTION 'One or more assignees do not exist';
  END IF;

  IF NOT public.is_editor() AND EXISTS (
    SELECT 1
    FROM unnest(COALESCE(p_placement_names, '{}'::text[])) requested(name)
    LEFT JOIN public.placements p ON p.name = requested.name
    WHERE p.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Only editors can create new placements';
  END IF;

  INSERT INTO public.tasks(
    id, title, description, team_id, status_id, priority, due_date, done_date,
    content_type, notes, editor_ids, designer_ids, links, files,
    custom_field_values, sort_order
  ) VALUES (
    v_task_id,
    p_task ->> 'title',
    COALESCE(p_task ->> 'description', ''),
    v_team_id,
    public.try_uuid(p_task ->> 'status_id'),
    COALESCE(NULLIF(p_task ->> 'priority', ''), 'medium'),
    NULLIF(p_task ->> 'due_date', '')::date,
    NULLIF(p_task ->> 'done_date', '')::date,
    NULLIF(p_task ->> 'content_type', ''),
    NULLIF(p_task ->> 'notes', ''),
    COALESCE(p_task -> 'editor_ids', '[]'::jsonb),
    COALESCE(p_task -> 'designer_ids', '[]'::jsonb),
    COALESCE(p_task -> 'links', '[]'::jsonb),
    COALESCE(p_task -> 'files', '[]'::jsonb),
    COALESCE(p_task -> 'custom_field_values', '{}'::jsonb),
    COALESCE((p_task ->> 'sort_order')::integer, 0)
  )
  ON CONFLICT (id) DO UPDATE
  SET title = EXCLUDED.title,
      description = EXCLUDED.description,
      team_id = EXCLUDED.team_id,
      status_id = EXCLUDED.status_id,
      priority = EXCLUDED.priority,
      due_date = EXCLUDED.due_date,
      done_date = EXCLUDED.done_date,
      content_type = EXCLUDED.content_type,
      notes = EXCLUDED.notes,
      editor_ids = EXCLUDED.editor_ids,
      designer_ids = EXCLUDED.designer_ids,
      links = EXCLUDED.links,
      files = EXCLUDED.files,
      custom_field_values = EXCLUDED.custom_field_values,
      sort_order = EXCLUDED.sort_order;

  DELETE FROM public.task_assignees a
  WHERE a.task_id = v_task_id
    AND NOT (a.member_id = ANY(COALESCE(p_assignee_ids, '{}'::uuid[])));

  INSERT INTO public.task_assignees(task_id, member_id, sort_order)
  SELECT v_task_id, requested.member_id, min(requested.ordinality)::integer - 1
  FROM unnest(COALESCE(p_assignee_ids, '{}'::uuid[])) WITH ORDINALITY
       AS requested(member_id, ordinality)
  GROUP BY requested.member_id
  ON CONFLICT (task_id, member_id) DO UPDATE
  SET sort_order = EXCLUDED.sort_order;

  IF v_can_mutate_placements THEN
    IF public.is_editor() THEN
      INSERT INTO public.placements(name)
      SELECT DISTINCT btrim(name)
      FROM unnest(COALESCE(p_placement_names, '{}'::text[])) requested(name)
      WHERE btrim(name) <> ''
      ON CONFLICT (name) DO NOTHING;
    END IF;

    DELETE FROM public.task_placements tp
    WHERE tp.task_id = v_task_id
      AND NOT EXISTS (
        SELECT 1
        FROM public.placements p
        WHERE p.id = tp.placement_id
          AND p.name = ANY(COALESCE(p_placement_names, '{}'::text[]))
      );

    INSERT INTO public.task_placements(task_id, placement_id)
    SELECT DISTINCT v_task_id, p.id
    FROM public.placements p
    WHERE p.name = ANY(COALESCE(p_placement_names, '{}'::text[]))
    ON CONFLICT DO NOTHING;
  END IF;

  PERFORM public.rebuild_task_access_grants(v_task_id);
  RETURN v_task_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_task_context(
  p_task_id uuid,
  p_context_team_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_home_team_id uuid;
  v_context_team_id uuid;
BEGIN
  SELECT t.team_id INTO v_home_team_id
  FROM public.tasks t
  WHERE t.id = p_task_id AND t.deleted_at IS NULL;
  IF v_home_team_id IS NULL THEN
    RAISE EXCEPTION 'Task unavailable';
  END IF;

  v_context_team_id := COALESCE(p_context_team_id, v_home_team_id);
  IF v_context_team_id <> v_home_team_id AND NOT EXISTS (
    SELECT 1 FROM public.task_team_links link
    WHERE link.task_id = p_task_id AND link.team_id = v_context_team_id
  ) THEN
    RAISE EXCEPTION 'Invalid task context';
  END IF;
  RETURN v_context_team_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_comment_mentions(
  p_task_id uuid,
  p_context_team_id uuid,
  p_mentioned_profile_ids uuid[]
)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expected_count integer;
  v_existing_count integer;
BEGIN
  v_expected_count := cardinality(ARRAY(
    SELECT DISTINCT unnest(COALESCE(p_mentioned_profile_ids, '{}'::uuid[]))
  ));
  SELECT count(*) INTO v_existing_count
  FROM public.profiles p
  WHERE p.id = ANY(COALESCE(p_mentioned_profile_ids, '{}'::uuid[]));
  IF v_existing_count <> v_expected_count THEN
    RAISE EXCEPTION 'One or more mentioned profiles do not exist';
  END IF;

  IF NOT public.is_full_access() AND EXISTS (
    SELECT 1
    FROM unnest(COALESCE(p_mentioned_profile_ids, '{}'::uuid[])) mentioned(profile_id)
    WHERE NOT EXISTS (
      SELECT 1
      FROM public.task_access_grants g
      WHERE g.task_id = p_task_id
        AND g.context_team_id = p_context_team_id
        AND g.profile_id = mentioned.profile_id
    )
  ) THEN
    RAISE EXCEPTION 'External collaborators may mention only existing task participants';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_task_comment_with_mentions(
  p_task_id uuid,
  p_content text,
  p_context_team_id uuid DEFAULT NULL,
  p_mentioned_profile_ids uuid[] DEFAULT '{}'::uuid[]
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_profile_id uuid;
  v_context_team_id uuid;
  v_comment_id uuid;
  v_grants_access boolean;
BEGIN
  v_profile_id := public.current_profile_id();
  IF v_profile_id IS NULL THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;
  IF btrim(COALESCE(p_content, '')) = '' THEN
    RAISE EXCEPTION 'Comment cannot be empty';
  END IF;
  IF NOT public.is_full_access() AND NOT public.has_related_task_access(p_task_id) THEN
    RAISE EXCEPTION 'Task unavailable';
  END IF;

  v_context_team_id := public.resolve_task_context(p_task_id, p_context_team_id);
  IF NOT public.is_full_access()
     AND NOT public.has_related_context_access(p_task_id, v_context_team_id) THEN
    RAISE EXCEPTION 'Task context unavailable';
  END IF;
  PERFORM public.validate_comment_mentions(
    p_task_id, v_context_team_id, p_mentioned_profile_ids
  );
  v_grants_access := public.is_full_access();

  INSERT INTO public.task_comments(task_id, user_id, content, context_team_id)
  VALUES (p_task_id, v_profile_id, btrim(p_content), v_context_team_id)
  RETURNING id INTO v_comment_id;

  INSERT INTO public.task_comment_mentions(
    comment_id, task_id, profile_id, context_team_id, grants_access
  )
  SELECT v_comment_id, p_task_id, mentioned.profile_id, v_context_team_id, v_grants_access
  FROM (
    SELECT DISTINCT unnest(COALESCE(p_mentioned_profile_ids, '{}'::uuid[])) AS profile_id
  ) mentioned;

  PERFORM public.rebuild_task_access_grants(p_task_id);
  RETURN v_comment_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_task_comment_with_mentions(
  p_comment_id uuid,
  p_content text,
  p_context_team_id uuid DEFAULT NULL,
  p_mentioned_profile_ids uuid[] DEFAULT '{}'::uuid[]
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_comment public.task_comments%ROWTYPE;
  v_profile_id uuid;
  v_context_team_id uuid;
  v_grants_access boolean;
  v_previously_granting_profile_ids uuid[] := '{}'::uuid[];
BEGIN
  SELECT * INTO v_comment
  FROM public.task_comments
  WHERE id = p_comment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Comment not found';
  END IF;

  v_profile_id := public.current_profile_id();
  IF v_comment.user_id <> v_profile_id
     AND NOT (public.is_full_access() AND public.is_editor()) THEN
    RAISE EXCEPTION 'Only the comment author or an editor can edit this comment';
  END IF;
  IF btrim(COALESCE(p_content, '')) = '' THEN
    RAISE EXCEPTION 'Comment cannot be empty';
  END IF;
  IF NOT public.is_full_access() AND NOT public.has_related_task_access(v_comment.task_id) THEN
    RAISE EXCEPTION 'Task unavailable';
  END IF;

  v_context_team_id := public.resolve_task_context(
    v_comment.task_id, COALESCE(p_context_team_id, v_comment.context_team_id)
  );
  IF NOT public.is_full_access()
     AND NOT public.has_related_context_access(v_comment.task_id, v_context_team_id) THEN
    RAISE EXCEPTION 'Task context unavailable';
  END IF;
  PERFORM public.validate_comment_mentions(
    v_comment.task_id, v_context_team_id, p_mentioned_profile_ids
  );
  v_grants_access := public.is_full_access();

  -- A downgrade must prevent *new* grants, but editing a comment should not
  -- silently revoke mentions that were legitimately created while its author
  -- had full access. Moving a mention to another context is still a new grant.
  SELECT COALESCE(array_agg(m.profile_id), '{}'::uuid[])
  INTO v_previously_granting_profile_ids
  FROM public.task_comment_mentions m
  WHERE m.comment_id = p_comment_id
    AND m.context_team_id = v_context_team_id
    AND m.grants_access;

  UPDATE public.task_comments
  SET content = btrim(p_content),
      context_team_id = v_context_team_id,
      updated_at = now()
  WHERE id = p_comment_id;

  DELETE FROM public.task_comment_mentions WHERE comment_id = p_comment_id;
  INSERT INTO public.task_comment_mentions(
    comment_id, task_id, profile_id, context_team_id, grants_access
  )
  SELECT p_comment_id, v_comment.task_id, mentioned.profile_id,
         v_context_team_id,
         v_grants_access OR mentioned.profile_id = ANY(v_previously_granting_profile_ids)
  FROM (
    SELECT DISTINCT unnest(COALESCE(p_mentioned_profile_ids, '{}'::uuid[])) AS profile_id
  ) mentioned;

  PERFORM public.rebuild_task_access_grants(v_comment.task_id);
  RETURN p_comment_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- 9. Minimal external bootstrap RPCs
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_my_task_access_contexts()
RETURNS TABLE(task_id uuid, context_team_id uuid)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT DISTINCT g.task_id, g.context_team_id
  FROM public.task_access_grants g
  JOIN public.tasks t ON t.id = g.task_id AND t.deleted_at IS NULL
  WHERE g.profile_id = public.current_profile_id()
    AND (
      g.context_team_id = t.team_id
      OR EXISTS (
        SELECT 1 FROM public.task_team_links link
        WHERE link.task_id = g.task_id
          AND link.team_id = g.context_team_id
      )
    )
  ORDER BY g.context_team_id, g.task_id
$$;

CREATE OR REPLACE FUNCTION public.get_visible_profile_summaries()
RETURNS TABLE(id uuid, name text, avatar text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH my_contexts AS (
    SELECT DISTINCT g.task_id, g.context_team_id
    FROM public.task_access_grants g
    JOIN public.tasks t ON t.id = g.task_id AND t.deleted_at IS NULL
    WHERE g.profile_id = public.current_profile_id()
  ), my_tasks AS (
    SELECT DISTINCT mc.task_id FROM my_contexts mc
  ), visible_profile_ids AS (
    SELECT public.current_profile_id() AS profile_id
    UNION
    SELECT p.id
    FROM public.profiles p
    WHERE public.is_full_access()
    UNION
    SELECT g.profile_id
    FROM public.task_access_grants g
    JOIN my_contexts mc
      ON mc.task_id = g.task_id
     AND mc.context_team_id = g.context_team_id
    UNION
    SELECT g.profile_id
    FROM public.task_access_grants g
    JOIN public.tasks t
      ON t.id = g.task_id
     AND t.team_id = g.context_team_id
    JOIN my_tasks mt ON mt.task_id = g.task_id
    UNION
    SELECT c.user_id
    FROM public.task_comments c
    JOIN my_tasks mt ON mt.task_id = c.task_id
    UNION
    SELECT a.user_id
    FROM public.task_activity a
    JOIN my_tasks mt ON mt.task_id = a.task_id
    UNION
    SELECT m.profile_id
    FROM public.task_comment_mentions m
    JOIN my_tasks mt ON mt.task_id = m.task_id
  )
  SELECT p.id, p.name, p.avatar
  FROM public.profiles p
  JOIN visible_profile_ids visible ON visible.profile_id = p.id
  ORDER BY p.name, p.id
$$;

-- -----------------------------------------------------------------------------
-- 10. RLS: full users keep current behavior; external users get only task scope
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.external_comment_notification_allowed(
  p_recipient_id uuid,
  p_entity_data jsonb
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_task_id uuid;
  v_context_team_id uuid;
  v_comment_id uuid;
BEGIN
  v_task_id := public.try_uuid(p_entity_data ->> 'taskId');
  v_context_team_id := public.try_uuid(
    COALESCE(p_entity_data ->> 'contextTeamId', p_entity_data ->> 'teamId')
  );
  v_comment_id := public.try_uuid(p_entity_data ->> 'commentId');
  IF v_task_id IS NULL OR v_context_team_id IS NULL OR v_comment_id IS NULL THEN
    RETURN false;
  END IF;
  RETURN public.has_related_context_access(v_task_id, v_context_team_id)
    AND EXISTS (
      SELECT 1
      FROM public.task_access_grants g
      WHERE g.task_id = v_task_id
        AND g.context_team_id = v_context_team_id
        AND g.profile_id = p_recipient_id
    )
    AND EXISTS (
      SELECT 1
      FROM public.task_comment_mentions m
      JOIN public.task_comments c ON c.id = m.comment_id
      WHERE m.comment_id = v_comment_id
        AND m.task_id = v_task_id
        AND m.context_team_id = v_context_team_id
        AND m.profile_id = p_recipient_id
        AND c.user_id = public.current_profile_id()
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.notification_preferences preference
      WHERE preference.user_id = p_recipient_id
        AND preference.category = 'mentions'
        AND preference.channel = 'in_app'
        AND preference.enabled = false
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.external_notification_visible(
  p_type text,
  p_entity_data jsonb
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p_type IN (
           'task_assigned', 'task_status_changed', 'task_updated',
           'task_unassigned', 'task_deleted', 'task_deadline_reminder',
           'comment_mention'
         )
    AND (p_type <> 'comment_mention' OR NOT COALESCE(p_entity_data ? 'ticketId', false))
    AND public.try_uuid(p_entity_data ->> 'taskId') IS NOT NULL
    AND public.try_uuid(
          COALESCE(p_entity_data ->> 'contextTeamId', p_entity_data ->> 'teamId')
        ) IS NOT NULL
    AND public.has_related_context_access(
          public.try_uuid(p_entity_data ->> 'taskId'),
          public.try_uuid(
            COALESCE(p_entity_data ->> 'contextTeamId', p_entity_data ->> 'teamId')
          )
        )
$$;

-- A persisted structured mention is one notification event. This also makes a
-- direct retry after a network timeout idempotent without affecting legacy
-- support-ticket mentions, which do not carry commentId.
CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_task_comment_mention_once
  ON public.notifications(recipient_id, ((entity_data ->> 'commentId')))
  WHERE type = 'comment_mention' AND entity_data ? 'commentId';

CREATE OR REPLACE FUNCTION public.claim_external_notification_delivery(
  p_comment_id uuid,
  p_recipient_id uuid,
  p_channel text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_inserted_count integer;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required';
  END IF;
  IF p_channel NOT IN ('email', 'telegram') THEN
    RAISE EXCEPTION 'Invalid notification channel';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.task_comment_mentions mention
    WHERE mention.comment_id = p_comment_id
      AND mention.profile_id = p_recipient_id
  ) THEN
    RAISE EXCEPTION 'Persisted structured mention not found';
  END IF;

  INSERT INTO public.external_notification_deliveries(
    comment_id, recipient_id, channel
  ) VALUES (
    p_comment_id, p_recipient_id, p_channel
  )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
  RETURN v_inserted_count = 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_external_notification_delivery_sent(
  p_comment_id uuid,
  p_recipient_id uuid,
  p_channel text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_updated_count integer;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required';
  END IF;
  IF p_channel NOT IN ('email', 'telegram') THEN
    RAISE EXCEPTION 'Invalid notification channel';
  END IF;

  UPDATE public.external_notification_deliveries
  SET sent_at = now()
  WHERE comment_id = p_comment_id
    AND recipient_id = p_recipient_id
    AND channel = p_channel
    AND sent_at IS NULL;
  GET DIAGNOSTICS v_updated_count = ROW_COUNT;
  RETURN v_updated_count = 1;
END;
$$;

-- Full-access users may legitimately produce repeated task events, but an
-- outbound transport must not become an unbounded relay to a related-only
-- recipient. The service role atomically claims one delivery per rolling minute
-- for the exact recipient/task/context/type/channel tuple. A NULL claim means a
-- delivery was claimed in the preceding 60 seconds. Failed deliveries may retry
-- after that interval; successful delivery is recorded by the opaque claim ID.
CREATE OR REPLACE FUNCTION public.claim_restricted_task_notification_delivery(
  p_recipient_id uuid,
  p_task_id uuid,
  p_context_team_id uuid,
  p_notification_type text,
  p_channel text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_claim_id uuid;
  v_now timestamptz := clock_timestamp();
  v_window_started_at timestamptz := date_trunc('minute', v_now);
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required';
  END IF;
  IF p_notification_type IS NULL OR NOT (
    p_notification_type = ANY (ARRAY[
      'task_assigned', 'task_status_changed', 'task_updated',
      'task_deadline_reminder'
    ]::text[])
  ) THEN
    RAISE EXCEPTION 'Invalid restricted task notification type';
  END IF;
  IF p_channel IS NULL OR NOT (p_channel = ANY (ARRAY['email', 'telegram']::text[])) THEN
    RAISE EXCEPTION 'Invalid notification channel';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.profiles recipient
    JOIN public.task_access_grants grant_row
      ON grant_row.profile_id = recipient.id
     AND grant_row.task_id = p_task_id
     AND grant_row.context_team_id = p_context_team_id
    JOIN public.tasks task_row
      ON task_row.id = grant_row.task_id
     AND task_row.deleted_at IS NULL
    WHERE recipient.id = p_recipient_id
      AND recipient.access_scope = 'related_only'
  ) THEN
    RAISE EXCEPTION 'Restricted recipient has no live task context access';
  END IF;

  -- Serialize only this delivery tuple. Hash collisions can at worst serialize
  -- unrelated claims; they cannot authorize or suppress a committed claim.
  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      concat_ws(
        '|',
        p_recipient_id::text,
        p_task_id::text,
        p_context_team_id::text,
        p_notification_type,
        p_channel
      ),
      0
    )
  );

  IF EXISTS (
    SELECT 1
    FROM public.restricted_task_notification_deliveries delivery
    WHERE delivery.recipient_id = p_recipient_id
      AND delivery.task_id = p_task_id
      AND delivery.context_team_id = p_context_team_id
      AND delivery.notification_type = p_notification_type
      AND delivery.channel = p_channel
      AND delivery.claimed_at > v_now - interval '60 seconds'
  ) THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.restricted_task_notification_deliveries(
    recipient_id,
    task_id,
    context_team_id,
    notification_type,
    channel,
    window_started_at
  ) VALUES (
    p_recipient_id,
    p_task_id,
    p_context_team_id,
    p_notification_type,
    p_channel,
    v_window_started_at
  )
  ON CONFLICT DO NOTHING
  RETURNING claim_id INTO v_claim_id;

  RETURN v_claim_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_restricted_task_notification_delivery_sent(
  p_claim_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_updated_count integer;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required';
  END IF;

  UPDATE public.restricted_task_notification_deliveries
  SET sent_at = now()
  WHERE claim_id = p_claim_id
    AND sent_at IS NULL;
  GET DIAGNOSTICS v_updated_count = ROW_COUNT;
  RETURN v_updated_count = 1;
END;
$$;

ALTER TABLE public.task_comment_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_access_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_access_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.external_access_migration_report ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.external_notification_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restricted_task_notification_deliveries ENABLE ROW LEVEL SECURITY;

-- Replace every public-table policy touched by this feature. Recreating the
-- matrix avoids an older permissive policy being OR'ed with a restrictive one.
DO $$
DECLARE
  policy_row record;
BEGIN
  FOR policy_row IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = ANY (ARRAY[
        'profiles', 'teams', 'tasks', 'task_assignees', 'placements',
        'task_placements', 'team_statuses', 'team_content_types',
        'custom_properties', 'absences', 'shifts', 'permissions',
        'activity_log', 'app_settings', 'notifications', 'telegram_links',
        'task_comments', 'docs', 'user_team_orders', 'task_team_links',
        'team_placements', 'task_activity', 'task_deadline_reminders',
        'notification_preferences', 'team_members', 'team_hidden_columns',
        'team_person_field_config', 'tickets', 'ticket_comments',
        'task_comment_mentions', 'task_access_grants',
        'task_access_revisions', 'external_access_migration_report',
        'external_notification_deliveries',
        'restricted_task_notification_deliveries'
      ])
  LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I.%I',
      policy_row.policyname,
      policy_row.schemaname,
      policy_row.tablename
    );
  END LOOP;
END;
$$;

-- profiles: external users can read only themselves. Participant summaries are
-- intentionally column-limited by get_visible_profile_summaries().
CREATE POLICY profiles_select_scope ON public.profiles
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR auth_user_id = auth.uid());
CREATE POLICY profiles_insert_admin ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND public.is_admin());
CREATE POLICY profiles_delete_admin ON public.profiles
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_admin());

CREATE POLICY teams_select_scope ON public.teams
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(id));
CREATE POLICY teams_mutate_editors ON public.teams
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY tasks_select_scope ON public.tasks
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    OR (deleted_at IS NULL AND public.has_related_task_access(id))
  );
CREATE POLICY tasks_insert_full ON public.tasks
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access());
CREATE POLICY tasks_update_full ON public.tasks
  FOR UPDATE TO authenticated
  USING (public.is_full_access())
  WITH CHECK (public.is_full_access());
CREATE POLICY tasks_delete_full ON public.tasks
  FOR DELETE TO authenticated
  USING (
    public.is_full_access()
    AND (
      public.is_editor()
      OR team_id = (SELECT ap.team_id FROM public.auth_profile() ap)
    )
  );

CREATE POLICY task_assignees_select_scope ON public.task_assignees
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));
CREATE POLICY task_assignees_mutate_full ON public.task_assignees
  FOR ALL TO authenticated
  USING (public.is_full_access())
  WITH CHECK (public.is_full_access());

CREATE POLICY placements_select_scope ON public.placements
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    OR EXISTS (
      SELECT 1
      FROM public.task_placements tp
      WHERE tp.placement_id = placements.id
        AND public.has_related_task_access(tp.task_id)
    )
  );
CREATE POLICY placements_insert_editors ON public.placements
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY placements_update_editors ON public.placements
  FOR UPDATE TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY placements_delete_editors ON public.placements
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_editor());

CREATE POLICY task_placements_select_scope ON public.task_placements
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));
CREATE POLICY task_placements_mutate_full ON public.task_placements
  FOR ALL TO authenticated
  USING (
    public.is_full_access()
    AND (
      public.is_editor()
      OR EXISTS (
        SELECT 1 FROM public.tasks t
        WHERE t.id = task_placements.task_id
          AND t.team_id = (SELECT ap.team_id FROM public.auth_profile() ap)
      )
    )
  )
  WITH CHECK (
    public.is_full_access()
    AND (
      public.is_editor()
      OR EXISTS (
        SELECT 1 FROM public.tasks t
        WHERE t.id = task_placements.task_id
          AND t.team_id = (SELECT ap.team_id FROM public.auth_profile() ap)
      )
    )
  );

CREATE POLICY team_statuses_select_scope ON public.team_statuses
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY team_statuses_mutate_editors ON public.team_statuses
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY team_content_types_select_scope ON public.team_content_types
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY team_content_types_mutate_editors ON public.team_content_types
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY custom_properties_select_scope ON public.custom_properties
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY custom_properties_mutate_editors ON public.custom_properties
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY absences_select_full ON public.absences
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY absences_insert_full ON public.absences
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_full_access()
    AND (member_id = public.current_profile_id() OR public.is_editor())
  );
CREATE POLICY absences_update_full ON public.absences
  FOR UPDATE TO authenticated
  USING (
    public.is_full_access()
    AND (
      public.is_admin()
      OR (member_id = public.current_profile_id() AND status = 'pending')
    )
  )
  WITH CHECK (
    public.is_full_access()
    AND (public.is_admin() OR (status = 'pending' AND decided_by IS NULL))
  );
CREATE POLICY absences_delete_full ON public.absences
  FOR DELETE TO authenticated
  USING (
    public.is_full_access()
    AND (
      public.is_editor()
      OR (member_id = public.current_profile_id() AND status = 'pending')
    )
  );

CREATE POLICY shifts_select_full ON public.shifts
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY shifts_insert_editors ON public.shifts
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY shifts_update_editors ON public.shifts
  FOR UPDATE TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY shifts_delete_editors ON public.shifts
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_editor());

CREATE POLICY permissions_select_full ON public.permissions
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY permissions_mutate_editors ON public.permissions
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY activity_log_select_full ON public.activity_log
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY activity_log_insert_full ON public.activity_log
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND user_id = public.current_profile_id());

CREATE POLICY app_settings_select_full ON public.app_settings
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY app_settings_mutate_admin ON public.app_settings
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_admin())
  WITH CHECK (public.is_full_access() AND public.is_admin());

CREATE POLICY notifications_select_own_scope ON public.notifications
  FOR SELECT TO authenticated
  USING (
    recipient_id = public.current_profile_id()
    AND (
      public.is_full_access()
      OR public.external_notification_visible(type, entity_data)
    )
  );
CREATE POLICY notifications_insert_scope ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (
    actor_id = public.current_profile_id()
    AND (
      public.is_full_access()
      OR (
        type = 'comment_mention'
        AND public.external_comment_notification_allowed(recipient_id, entity_data)
      )
    )
  );
CREATE POLICY notifications_update_own_scope ON public.notifications
  FOR UPDATE TO authenticated
  USING (
    recipient_id = public.current_profile_id()
    AND (
      public.is_full_access()
      OR public.external_notification_visible(type, entity_data)
    )
  )
  WITH CHECK (recipient_id = public.current_profile_id());
CREATE POLICY notifications_delete_own_scope ON public.notifications
  FOR DELETE TO authenticated
  USING (
    recipient_id = public.current_profile_id()
    AND (
      public.is_full_access()
      OR public.external_notification_visible(type, entity_data)
    )
  );

CREATE POLICY telegram_links_select_own ON public.telegram_links
  FOR SELECT TO authenticated USING (profile_id = public.current_profile_id());
CREATE POLICY telegram_links_insert_own ON public.telegram_links
  FOR INSERT TO authenticated WITH CHECK (profile_id = public.current_profile_id());
CREATE POLICY telegram_links_update_own ON public.telegram_links
  FOR UPDATE TO authenticated
  USING (profile_id = public.current_profile_id())
  WITH CHECK (profile_id = public.current_profile_id());
CREATE POLICY telegram_links_delete_own ON public.telegram_links
  FOR DELETE TO authenticated USING (profile_id = public.current_profile_id());

CREATE POLICY task_comments_select_scope ON public.task_comments
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));
CREATE POLICY task_comments_delete_scope ON public.task_comments
  FOR DELETE TO authenticated
  USING (
    (public.is_full_access() AND public.is_admin())
    OR (
      user_id = public.current_profile_id()
      AND (public.is_full_access() OR public.has_related_task_access(task_id))
    )
  );

CREATE POLICY docs_select_full ON public.docs
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY docs_insert_admin ON public.docs
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND public.is_admin());
CREATE POLICY docs_update_admin ON public.docs
  FOR UPDATE TO authenticated
  USING (public.is_full_access() AND public.is_admin())
  WITH CHECK (public.is_full_access() AND public.is_admin());
CREATE POLICY docs_delete_admin ON public.docs
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_admin());

CREATE POLICY user_team_orders_full_own ON public.user_team_orders
  FOR ALL TO authenticated
  USING (public.is_full_access() AND user_id = public.current_profile_id())
  WITH CHECK (public.is_full_access() AND user_id = public.current_profile_id());

CREATE POLICY task_team_links_select_scope ON public.task_team_links
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    OR public.has_related_context_access(task_id, team_id)
  );
CREATE POLICY task_team_links_mutate_full ON public.task_team_links
  FOR ALL TO authenticated
  USING (
    public.is_full_access()
    AND (
      public.is_editor()
      OR team_id = (SELECT ap.team_id FROM public.auth_profile() ap)
    )
  )
  WITH CHECK (
    public.is_full_access()
    AND (
      public.is_editor()
      OR team_id = (SELECT ap.team_id FROM public.auth_profile() ap)
    )
  );

CREATE POLICY team_placements_select_scope ON public.team_placements
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY team_placements_insert_editors ON public.team_placements
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY team_placements_update_editors ON public.team_placements
  FOR UPDATE TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());
CREATE POLICY team_placements_delete_editors ON public.team_placements
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_editor());

CREATE POLICY task_activity_select_scope ON public.task_activity
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));
CREATE POLICY task_activity_insert_full ON public.task_activity
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND user_id = public.current_profile_id());

CREATE POLICY task_deadline_reminders_select_scope ON public.task_deadline_reminders
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));

CREATE POLICY notification_preferences_select_scope ON public.notification_preferences
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    OR (
      user_id = public.current_profile_id()
      AND category IN ('tasks', 'deadlines', 'mentions')
    )
  );
CREATE POLICY notification_preferences_insert_scope ON public.notification_preferences
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = public.current_profile_id()
    AND (public.is_full_access() OR category IN ('tasks', 'deadlines', 'mentions'))
  );
CREATE POLICY notification_preferences_update_scope ON public.notification_preferences
  FOR UPDATE TO authenticated
  USING (
    user_id = public.current_profile_id()
    AND (public.is_full_access() OR category IN ('tasks', 'deadlines', 'mentions'))
  )
  WITH CHECK (
    user_id = public.current_profile_id()
    AND (public.is_full_access() OR category IN ('tasks', 'deadlines', 'mentions'))
  );
CREATE POLICY notification_preferences_delete_scope ON public.notification_preferences
  FOR DELETE TO authenticated
  USING (
    user_id = public.current_profile_id()
    AND (public.is_full_access() OR category IN ('tasks', 'deadlines', 'mentions'))
  );

CREATE POLICY team_members_select_full ON public.team_members
  FOR SELECT TO authenticated USING (public.is_full_access());
CREATE POLICY team_members_mutate_admin ON public.team_members
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_admin())
  WITH CHECK (public.is_full_access() AND public.is_admin());

CREATE POLICY team_hidden_columns_select_scope ON public.team_hidden_columns
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY team_hidden_columns_mutate_editors ON public.team_hidden_columns
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY team_person_field_config_select_scope ON public.team_person_field_config
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.is_authorized_task_team(team_id));
CREATE POLICY team_person_field_config_mutate_editors ON public.team_person_field_config
  FOR ALL TO authenticated
  USING (public.is_full_access() AND public.is_editor())
  WITH CHECK (public.is_full_access() AND public.is_editor());

CREATE POLICY tickets_select_full ON public.tickets
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    AND (public.is_admin() OR reporter_id = public.current_profile_id())
  );
CREATE POLICY tickets_insert_full ON public.tickets
  FOR INSERT TO authenticated
  WITH CHECK (public.is_full_access() AND reporter_id = public.current_profile_id());
CREATE POLICY tickets_update_full ON public.tickets
  FOR UPDATE TO authenticated
  USING (
    public.is_full_access()
    AND (public.is_admin() OR reporter_id = public.current_profile_id())
  )
  WITH CHECK (public.is_full_access());
CREATE POLICY tickets_delete_admin ON public.tickets
  FOR DELETE TO authenticated
  USING (public.is_full_access() AND public.is_admin());

CREATE POLICY ticket_comments_select_full ON public.ticket_comments
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    AND EXISTS (
      SELECT 1 FROM public.tickets t
      WHERE t.id = ticket_comments.ticket_id
        AND (public.is_admin() OR t.reporter_id = public.current_profile_id())
    )
  );
CREATE POLICY ticket_comments_insert_full ON public.ticket_comments
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_full_access()
    AND user_id = public.current_profile_id()
    AND EXISTS (
      SELECT 1 FROM public.tickets t
      WHERE t.id = ticket_comments.ticket_id
        AND (public.is_admin() OR t.reporter_id = public.current_profile_id())
    )
  );
CREATE POLICY ticket_comments_update_full ON public.ticket_comments
  FOR UPDATE TO authenticated
  USING (
    public.is_full_access()
    AND (public.is_admin() OR user_id = public.current_profile_id())
  )
  WITH CHECK (public.is_full_access());
CREATE POLICY ticket_comments_delete_full ON public.ticket_comments
  FOR DELETE TO authenticated
  USING (
    public.is_full_access()
    AND (public.is_admin() OR user_id = public.current_profile_id())
  );

CREATE POLICY task_comment_mentions_select_scope ON public.task_comment_mentions
  FOR SELECT TO authenticated
  USING (public.is_full_access() OR public.has_related_task_access(task_id));

CREATE POLICY task_access_grants_select_scope ON public.task_access_grants
  FOR SELECT TO authenticated
  USING (
    public.is_full_access()
    OR (
      profile_id = public.current_profile_id()
      AND public.has_related_task_access(task_id)
    )
  );

CREATE POLICY task_access_revisions_select_own ON public.task_access_revisions
  FOR SELECT TO authenticated
  USING (profile_id = public.current_profile_id());

CREATE POLICY external_access_report_admin ON public.external_access_migration_report
  FOR SELECT TO authenticated
  USING (public.is_full_access() AND public.is_admin());

-- RLS determines which notification row belongs to the caller; column grants
-- additionally ensure the only mutable value is the read marker. Without this,
-- an owner could rewrite type, message, actor, recipient, or entity metadata.
REVOKE UPDATE ON TABLE public.notifications FROM PUBLIC, anon, authenticated;
GRANT UPDATE(read) ON TABLE public.notifications TO authenticated;

-- -----------------------------------------------------------------------------
-- 11. Function privileges and Realtime
-- -----------------------------------------------------------------------------

REVOKE ALL ON FUNCTION public.compute_task_access_grants(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.bump_task_access_revision(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.rebuild_task_access_grants(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.resolve_task_context(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_comment_mentions(uuid, uuid, uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.jsonb_profile_ids(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.legacy_comment_mention_starts(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.legacy_profile_mention_at(text, text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.legacy_profile_mention_positions(text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.move_home_comment_contexts()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.remap_linked_comment_contexts_before_team_delete()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.current_profile_id() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.current_access_scope() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_full_access() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_related_task_access(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_related_context_access(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_authorized_task_team(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.external_comment_notification_allowed(uuid, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.external_notification_visible(text, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_own_profile(text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_member_access_scope(uuid, text, uuid[], text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.save_task_with_relations(jsonb, uuid[], text[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_task_comment_with_mentions(uuid, text, uuid, uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_task_comment_with_mentions(uuid, text, uuid, uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_my_task_access_contexts() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_visible_profile_summaries() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_invited_profile(uuid, text, text, text, text, uuid, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_external_notification_delivery(uuid, uuid, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mark_external_notification_delivery_sent(uuid, uuid, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_restricted_task_notification_delivery(uuid, uuid, uuid, text, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mark_restricted_task_notification_delivery_sent(uuid)
  FROM PUBLIC, anon, authenticated;

-- These pre-existing helpers are needed by policies but must never be callable
-- anonymously after the project's default function grants are applied.
REVOKE ALL ON FUNCTION public.auth_profile() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_editor() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.try_uuid(text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.current_profile_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_access_scope() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_full_access() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_related_task_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_related_context_access(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_authorized_task_team(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.external_comment_notification_allowed(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.external_notification_visible(text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auth_profile() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_editor() TO authenticated;
GRANT EXECUTE ON FUNCTION public.try_uuid(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_own_profile(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_member_access_scope(uuid, text, uuid[], text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_task_with_relations(jsonb, uuid[], text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_task_comment_with_mentions(uuid, text, uuid, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_task_comment_with_mentions(uuid, text, uuid, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_task_access_contexts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_visible_profile_summaries() TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_invited_profile(uuid, text, text, text, text, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_external_notification_delivery(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_external_notification_delivery_sent(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_restricted_task_notification_delivery(uuid, uuid, uuid, text, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_restricted_task_notification_delivery_sent(uuid)
  TO service_role;

REVOKE ALL ON TABLE public.external_notification_deliveries
  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.external_notification_deliveries
  TO service_role;

REVOKE ALL ON TABLE public.restricted_task_notification_deliveries
  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.restricted_task_notification_deliveries
  TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'task_access_revisions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.task_access_revisions;
  END IF;
END;
$$;

ALTER TABLE public.task_comments REPLICA IDENTITY FULL;

COMMIT;
